// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cloudBig': string;
  'cloudSmall': string;
  'pikachu': string;
  'pokeBall': string;
  'root': string;
  'smallPokeBall': string;
}
export const cssExports: CssExports;
export default cssExports;
