// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities': string;
  'abilitiesText': string;
  'abilitiesTitle': string;
  'body': string;
  'capabilities': string;
  'capability': string;
  'capabilityName': string;
  'capabilityValue': string;
  'close': string;
  'generation': string;
  'header': string;
  'healthyPoints': string;
  'idLabel': string;
  'image': string;
  'imageWrapper': string;
  'info': string;
  'infoTitle': string;
  'label': string;
  'labelWrap': string;
  'pokemonName': string;
  'rate': string;
  'row': string;
  'strength': string;
  'strengthColumn': string;
  'strengthProgress': string;
  'strengthProgressExp': string;
  'strengthProgressHp': string;
  'strengthTitle': string;
  'strengthValue': string;
  'value': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
