// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities': string;
  'body': string;
  'close': string;
  'generation': string;
  'header': string;
  'healthyPoints': string;
  'idLabel': string;
  'image': string;
  'imageWrapper': string;
  'info': string;
  'infoTitle': string;
  'pokemonName': string;
  'rate': string;
  'row': string;
  'value': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
